#!/bin/bash

#presence test
./present
rouge='\e[0;31m'                                                                
vert='\e[1;32m'                                                                 
neutre='\e[0;m'        

echo -e "\n\n${vert}start of configuration\n${neutre}"
echo "config i3"
cp -r .i3/ ~/.config/
echo "config polybar"
cp -r .polybar/ ~/.config/
echo "dossier start"
cp -r start/ ~/.start
echo "xinitrc"
cp .xinitrc ~/.xinitrc
echo "zshrc"
cp .zshrc ~/.zshrc
cp -r .bash/ ~/.config/bash

if [ $SHELL != "/usr/bin/zsh" ];then 
    echo -e "${rouge}change of interpreter required"
    chsh -s /usr/bin/zsh                                                             
fi 

echo -e "${vert}END"

