#!/bin/bash

#presence test
#./present

echo " "
echo "start of configuration"
echo "config i3"
cp -r .i3/ ~/.config/
echo "config polybar"
cp -r .polybar/ ~/.config/
echo "dossier start"
cp -r start/ ~/.start
echo "xinitrc"
cp .xinitrc ~/.xinitrc

echo "END"

