#!/bin/bash
#presence test

testPackage=('kdeconnect' 'mpd' 'albert' 'devmon' 'blueman' 'compton' 'numlockx' 'firefox' 'i3')
noPresent=()

for package in ${testPackage[*]}
do
	if  pacman -Qs  $package > /dev/null
	then
		echo "$package present"
	else 
		echo "$package not present"
		noPresent=( "${noPresent[@]}" $package)
	fi
done

if [ -z "$noPresent" ];then
	echo "no download"
else
	pacman -S ${noPresent[*]}
fi


