#!/bin/bash
while [ '1' -eq '1' ];
do
	echo $(feh --bg-scale ~/.start/Wallpaper/galaxy1.jpg)
	sleep '300'
	echo $(feh --bg-scale ~/.start/Wallpaper/rick.jpg)
	sleep '300'
	echo $(feh --bg-scale ~/.start/Wallpaper/doom.jpg)
	sleep '300'
	echo $(feh --bg-scale ~/.start/Wallpaper/Battlefront_II.jpg)
	sleep '300'
	echo $(feh --bg-scale ~/.start/Wallpaper/galaxy2)
	sleep '300'
	echo $(feh --bg-scale ~/.start/Wallpaper/red.png)
	sleep '300'
	echo $(feh --bg-scale ~/.start/Wallpaper/2020-NOVITEC-Lamborghini-Aventador-SVJ.jpg)
	sleep '300'
	echo $(feh --bg-scale ~/.start/Wallpaper/joker.jpg)
	sleep '300'
done

